name: todo_flutter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.0
  flutter_svg: ^2.0.4
  flutter_native_splash: ^2.2.18
  country_picker: ^2.0.20
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  curved_navigation_bar: ^1.0.3
  provider: ^6.0.5
  pinput: ^2.2.31
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.0.2
  image_picker: ^1.0.1
  connectivity_plus: ^4.0.1
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_bloc: ^8.1.3
  table_calendar: ^3.0.9
  multi_select_flutter: ^4.1.3
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_app_name: ^0.1.0

dependency_overrides:
  xml: ^6.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background/login_background.png
    - assets/avatars/ai.png
    - assets/background/oceanlab_7.png
    - assets/background/login_background_new1.png
    - assets/background/login_background_new2.png
    - assets/launcher_icon/cellyfish_icon2.png
    - assets/icons/jellyfish1.png
    - assets/database/schema.sql
    - assets/icons/stats1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  background_image: assets/background/login_background_new2.png
  background_image_dark: assets/background/login_background_new2.png
  android_12:
    image: assets/background/login_background_new2.png
  fill: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/cellyfish_icon2.png"

flutter_app_name:
  name: "ASI"