// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa-tHm1WgdkxsbIGFcJAnVZIqsaG-6spE',
    appId: '1:223275758934:web:6a6243d863b4ea193092f7',
    messagingSenderId: '223275758934',
    projectId: 'todoflutter-efbf3',
    authDomain: 'todoflutter-efbf3.firebaseapp.com',
    storageBucket: 'todoflutter-efbf3.appspot.com',
    measurementId: 'G-BNE76PH0RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZe69T-XR25zyIoQHPXmXVZEi5PnQPu1s',
    appId: '1:223275758934:android:8a082ee5a13d07b43092f7',
    messagingSenderId: '223275758934',
    projectId: 'todoflutter-efbf3',
    storageBucket: 'todoflutter-efbf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATzn6JH-gfoXVtOHmbV1Rier3aRIxqGgw',
    appId: '1:223275758934:ios:4ce20fcb480a8b483092f7',
    messagingSenderId: '223275758934',
    projectId: 'todoflutter-efbf3',
    storageBucket: 'todoflutter-efbf3.appspot.com',
    iosClientId: '223275758934-o97k17k3rqfsd88sujvq4h1jojudjuhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATzn6JH-gfoXVtOHmbV1Rier3aRIxqGgw',
    appId: '1:223275758934:ios:4ce20fcb480a8b483092f7',
    messagingSenderId: '223275758934',
    projectId: 'todoflutter-efbf3',
    storageBucket: 'todoflutter-efbf3.appspot.com',
    iosClientId: '223275758934-o97k17k3rqfsd88sujvq4h1jojudjuhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFlutter',
  );
}
